# config/packages/twig.yaml
twig:
    exception_controller:  twig.controller.exception:showAction

    form_themes:
        # Default:
        - form_div_layout.html.twig

        # Bootstrap:
        - bootstrap_4_layout.html.twig
        - form/bootstrap_4_layout_no_label_error.html.twig
        - bootstrap_4_horizontal_layout.html.twig

        # Foundation
        - foundation_5_layout.html.twig
    globals:

        # Examples:
        pi:                  3.14

    # See http://twig.sensiolabs.org/doc/recipes.html#using-the-template-name-to-set-the-default-escaping-strategy
    #autoescape_service:        ~ # Example: 'my_service'
    #autoescape_service_method: ~ # use in combination with autoescape_service option
    #base_template_class:       base.html.twig
    cache:                     '%kernel.cache_dir%/twig'
    charset:                   '%kernel.charset%'
    debug:                     '%kernel.debug%'
    auto_reload:               ~
    #optimizations:             ~
    paths: ['%kernel.project_dir%/templates']
    strict_variables: '%kernel.debug%'

    date:
        format: d.m.Y, H:i:s
        interval_format: '%%d days'
        timezone: Europe/Paris
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
