index:
  path: /{_locale}
  defaults:
    _controller: App\Controller\MainController::indexAction
    _locale: fr

find_by_id:
  path: /{_locale}/session/findByID/{id}
  controller: App\Controller\SessionController::findByIDAction
  defaults:
    _locale: fr
  requirements:
    _locale: fr|en

recap_site:
  path: /{_locale}/site/{idSite}
  controller: App\Controller\SiteController::recapSiteAction
  defaults:
    _locale: fr
  requirements:
    _locale: fr|en

recherche_globale:
  path: /{_locale}/recherche
  controller: App\Controller\FormController::newFormAction
  defaults:
    _locale: fr
  requirements:
    _locale: fr|en