index:
  path: /{_locale}
  defaults:
    _controller: App\Controller\MainController::index
    _locale: fr

find_by_id:
  path: /{_locale}/session/findByID/{id}
  controller: App\Controller\SessionController::findByID
  requirements:
    _locale: fr|en

page_recap_site:
  path: /{_locale}/site/{idSite}
  controller: App\Controller\SiteController::page_recap_site
  requirements:
    _locale: fr|en

recherche_globale:
  path: /{_locale}/recherche
  controller: App\Controller\FormController::new
  defaults:
    _locale: fr
  requirements:
    _locale: fr|en